config/routes.rb
ClothingApp::Application.routes.draw do
  root 'static_pages#home'

  match '/help',    to: 'static_pages#help',    via: 'get'

  resources :items
  resources :models

  

  

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :model

	validates :thigh, :numericality => true 
	validates :knee, :numericality => true
	validates :leg_opening, :numericality => true
	validates :inseam, :numericality => true
	validates :tag_size, :numericality => true

	validates_numericality_of :waist, greater_than_or_equal_to: 26, less_than_or_equal_to: 42
	validates_numericality_of :front_rise, greater_than_or_equal_to: 8, less_than_or_equal_to: 13

	def self.true_waist_search(waist_size)
		if waist_size
			where('waist <= ?', (waist_size.to_d + 0.5))
			.where('waist >= ?', (waist_size.to_d - 0.5))
		else
			all
		end
	end

	def self.price_search(min, max)
		if min && max 
			joins(:model).where('models.price >= ?', min).where('models.price <= ?', max)
		else
			all 
		end
	end

	def self.fit_search(search)
		if search
			joins(:model).where('models.fit' => search)
		else
			all
		end
	end

	# def self.waist_search(waist_size)
	# 	if !waist_size.blank?
	# 		where('waist <= ?', (waist_size.to_d + 0.25))
	# 		.where('waist >= ?', (waist_size.to_d - 0.5))
	# 	else
	# 		all
	# 	end
	# end

	# def self.front_rise_search(waist_size, front_rise)
	# 	if !waist_size.blank? && front_rise != 0
	# 		where("ABS(front_rise/waist - ?) < 0.03", front_rise)
	# 	else
	# 		all
	# 	end	
	# end

	# def self.thigh_search(waist_size, thigh)
	# 	if !waist_size.blank? && thigh != 0
	# 		where("ABS(thigh/waist - ?) < 0.03", thigh)
	# 	else
	# 		all
	# 	end	
	# end

	# def self.knee_search(waist_size, knee)
	# 	if !waist_size.blank? && knee != 0
	# 		where("ABS(knee/waist - ?) < 0.03", knee)
	# 	else
	# 		all
	# 	end	
	# end

	# def self.leg_opening_search(waist_size, leg_opening)
	# 	if !waist_size.blank? && leg_opening != 0
	# 		where("ABS(leg_opening/waist - ?) < 0.03", leg_opening)
	# 	else
	# 		all
	# 	end	
	# end

	# def self.made_in_search(made_in)
	# 	if !made_in.blank?
	# 		where('made_in = ?', made_in)
	# 	else
	# 		all
	# 	end	
	# end

	# def self.fabric_origin_search(fabric_origin)
	# 	if !fabric_origin.blank?
	# 		where('fabric_origin = ?', fabric_origin)
	# 	else
	# 		all
	# 	end	
	# end

	# def self.color_search(color)
	# 	if !color.blank?
	# 		where('color = ?', color)
	# 	else
	# 		all
	# 	end	
	# end

	# def self.brand_search(brand)
	# 	if !brand.blank?
	# 		where('brand = ?', brand)
	# 	else
	# 		all
	# 	end	
	# end

	# def self.price_search(min, max)
	# 	if !min.blank? && !max.blank?
	# 		where('price >= ?', min)
	# 		.where('price <= ?', max)
	# 	elsif !min.blank?
	# 		where('price >= ?', min)
	# 	elsif !max.blank?
	# 		where('price <= ?', max)
	# 	else
	# 		all
	# 	end	
	# end

	# def self.denim_weight_search(min, max)
	# 	if !min.blank? && !max.blank?
	# 		where('denim_weight >= ?', min)
	# 		.where('denim_weight <= ?', max)
	# 	elsif !min.blank?
	# 		where('denim_weight >= ?', min)
	# 	elsif !max.blank?
	# 		where('denim_weight <= ?', max)
	# 	else
	# 		all
	# 	end	
	# end

	# def self.sanforized_search(sanforized)
	# 	case sanforized
	#     when "true"
	#       where('sanforized = ?', true)
	#     when "false"
	#       where('sanforized = ?', false)
	#     else
	#       all
	#     end
	# end

	# def self.selvedge_search(selvedge)
	# 	case selvedge
	#     when "true"
	#       where('selvedge = ?', true)
	#     when "false"
	#       where('selvedge = ?', false)
	#     else
	#       all
	#     end
	# end
end

app/models/model.rb
class Model < ActiveRecord::Base
	has_many :items

	validates :name, presence: true
	validates :brand, presence: true
	validates :fabric_origin, presence: true
	validates :made_in, presence: true
	validates :price, presence: true
	validates :denim_weight, presence: true
	validates :color, presence: true
	validates :fit, presence: true, :inclusion => { :in => ["straight", "slim straight", "skinny", "tapered"] }
	validates :url, presence: true

	validates_numericality_of :price, greater_than_or_equal_to: 20, less_than_or_equal_to: 1000

	# def self.price_search(min, max)
	# 	if min && max
	# 		where('price >= ?', min)
	# 		.where('price <= ?', max)
	# 	else
	# 		all
	# 	end
	# end

	# def self.fit_search(search)
	# 	if search
	# 		where('fit = ?', search)
	# 	else
	# 		all
	# 	end
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @waist = 1   
    @front_rise = 1
    @thigh =  1 
    @knee =  1
    @leg_opening = 1

    if params[:waist]
    	@waist = 	   params[:waist].to_d/params[:waist].to_d
    	@front_rise =  params[:front_rise].to_d/params[:waist].to_d
    	@thigh =	   params[:thigh].to_d/params[:waist].to_d
    	@knee =		   params[:knee].to_d/params[:waist].to_d
    	@leg_opening = params[:leg_opening].to_d/params[:waist].to_d
    end

    @items = Item.waist_search(params[:waist]).front_rise_search(params[:waist], @front_rise)
                 .thigh_search(params[:waist], @thigh).knee_search(params[:waist], @knee)
                 .leg_opening_search(params[:waist], @leg_opening).made_in_search(params[:made_in])
                 .fabric_origin_search(params[:fabric_origin]).color_search(params[:color])
                 .brand_search(params[:brand]).price_search(params[:min_price], params[:max_price])
                 .denim_weight_search(params[:min_denim_weight], params[:max_denim_weight])
                 .sanforized_search(params[:sanforized]).selvedge_search(params[:selvedge])

  end

  def show
  	@item = Item.find(params[:id])
  	@parse = ''
  	if params[:parse]
  		c = params[:parse]
  		@tag_size =    c.split(',')[0].split('Size ')[1].split(' (')[0] 
        @waist =       c.split('(')[1].split('"')[0] 
        @front_rise =  c.split('(')[1].split('"')[1].split(', ')[1] 
        @thigh =       c.split('(')[1].split('"')[2].split(', ')[1] 
        @knee =        c.split('(')[1].split('"')[3].split(', ')[1] 
        @leg_opening = c.split('(')[1].split('"')[5].split(', ')[1]
        @inseam =      c.split('(')[1].split('"')[4].split(', ')[1] 
    end
  end

  def new
  	@item = Item.new
  end

  def create
  	@item = Item.new(item_params)

  	if @item.save
  		flash[:success] = "New item added to database"
  		redirect_to items_path
  	else
  		render new_item_path
  	end
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def update
  	@item = Item.find(params[:id])

  	if @item.update_attributes(item_params)
  		flash[:success] = "Item has been updated"
  		redirect_to item_path(params[:id])
  	end
  end

  private

  def item_params
  	params.require(:item).permit(:name, :waist, 
							:front_rise, :thigh, :knee,
							:leg_opening, :price, :color,
							:brand, :link, :denim_weight,
							:sanforized, :inseam, :stretch,
							:tag_size, :made_in, :fabric_source,
							:selvedge)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	jeans = Item.true_waist_search(params[:waist])
  	jeans = jeans.price_search(params[:min_price], params[:max_price])
  	@jeans = jeans.fit_search(params[:fit])

  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/items/_index_table.html.erb
<table class="table table-striped">
	<tr>
		<th>Name</th>
		<th>Brand</th>
		<!-- <th>Front-Rise (Norm)</th>
		<th>Thigh (Norm)</th>
		<th>Knee (Norm)</th>
		<th>Leg-Opening (Norm)</th> -->
		<th>Tag-Size</th>
		<th>Waist</th>
		<th>Front-Rise</th>
		<th>Thigh</th>
		<th>Knee</th>
		<th>Leg-Opening</th>
		<th>Inseam</th>
		<th>Color</th>
		<th>Fabric Origin</th>
		<th>Manufacturing Country</th>
		<th>Denim-Weight</th>
		<th>Sanforization</th>
		<th>Stretch</th>
		<th>Selvedge</th>
		<th>Price</th>
	</tr>

	<% @items.each do |item| %>
		<tr>
			<td><%= item.name %></td>
			<td><%= item.brand %></td>
			<%#= number_with_precision(item.front_rise/item.waist - @front_rise, :precision => 4) %>
			<%#= number_with_precision(item.thigh/item.waist - @thigh, :precision => 4) %>
			<%#= number_with_precision(item.knee/item.waist - @knee, :precision => 4) %>
			<%#= number_with_precision(item.leg_opening/item.waist - @leg_opening, :precision => 4) %>
			<td><%= item.tag_size %></td>
			<td><%= item.waist %></td>
			<td><%= item.front_rise %></td>
			<td><%= item.thigh %></td>
			<td><%= number_with_precision(item.knee, :precision => 2) %></td>
			<td><%= number_with_precision(item.leg_opening, :precision => 2) %></td>
			<td><%= item.inseam %></td>
			<td><%= item.color %></td>
			<td><%= item.fabric_origin %></td>
			<td><%= item.made_in %></td>
			<td><%= item.denim_weight %></td>
			<td><%= item.sanforized %></td>
			<td><%= item.stretch %></td>
			<td><%= item.selvedge %></td>
			<td><%= item.price %></td>
			<td><%= link_to "Edit", edit_item_path(item) %></td>
		</tr>
	<% end %>	
  </table>

app/views/items/_scripts.html.erb
<% content_for :scripts do %>
	<script>
		$(document).ready(function(){
			// $(function() {
			// 	$('#show-slider').click(function(){
			// 		$("#slider-waist").slider({ disabled: false });
			// 	});
			// });

			$(function() {
			    $( "#slider-waist" ).slider({
			      value: [ <%= params[:waist].present? ? params[:waist] : 32 %> ],
			      min: 26,
			      max: 44,
			      step: 1,
			      slide: function( event, ui ) {
			      	$( "#amount-waist" ).val( ui.value + " inches" );
			        $( "#waist" ).val(ui.value);
			      }
			    });
			    $( "#amount-waist" ).val( $( "#slider-waist" ).slider( "value" ) + " inches" );
  			});

  			$(function() {
			    $( "#slider-front_rise" ).slider({
			      value: [ <%= params[:front_rise].present? ? params[:front_rise] : 10 %> ],
			      min: 8,
			      max: 13,
			      step: 0.02,
			      slide: function( event, ui ) {
			      	$( "#amount-front_rise" ).val( ui.value + " inches" );
			        $( "#front_rise" ).val(ui.value);
			      }
			    });
			    $( "#amount-front_rise" ).val( $( "#slider-front_rise" ).slider( "value" ) + " inches" );
  			});

  			$(function() {
			    $( "#slider-thigh" ).slider({
			      value: [ <%= params[:thigh].present? ? params[:thigh] : 11 %> ],
			      min: 9,
			      max: 15,
			      step: 0.02,
			      slide: function( event, ui ) {
			      	$( "#amount-thigh" ).val( ui.value + " inches" );
			        $( "#thigh" ).val(ui.value);
			      }
			    });
			    $( "#amount-thigh" ).val( $( "#slider-thigh" ).slider( "value" ) + " inches" );
  			});

  			$(function() {
			    $( "#slider-knee" ).slider({
			      value: [ <%= params[:knee].present? ? params[:knee] : 8 %> ],
			      min: 6,
			      max: 11,
			      step: 0.02,
			      slide: function( event, ui ) {
			      	$( "#amount-knee" ).val( ui.value + " inches" );
			        $( "#knee" ).val(ui.value);
			      }
			    });
			    $( "#amount-knee" ).val( $( "#slider-knee" ).slider( "value" ) + " inches" );
  			});

  			$(function() {
			    $( "#slider-leg_opening" ).slider({
			      value: [ <%= params[:leg_opening].present? ? params[:leg_opening] : 8 %> ],
			      min: 6,
			      max: 10,
			      step: 0.02,
			      slide: function( event, ui ) {
			      	$( "#amount-leg_opening" ).val( ui.value + " inches" );
			        $( "#leg_opening" ).val(ui.value);
			      }
			    });
			    $( "#amount-leg_opening" ).val( $( "#slider-leg_opening" ).slider( "value" ) + " inches" );
  			});

			$(function() {
			    $( "#slider-price" ).slider({
			      range: true,
			      min: 0,
			      max: 500,
			      step: 10,
			      values: [ <%= params[:min_price].present? ? params[:min_price] : 0 %>, 
			      			<%= params[:max_price].present? ? params[:max_price] : 500 %> ],
			      slide: function( event, ui ) {
			      	$( "#amount-price" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
			        $( "#min_price" ).val(ui.values[0]);
			        $( "#max_price" ).val(ui.values[1]);
			      }
			    });
			    $( "#amount-price" ).val( "$" + $( "#slider-price" ).slider( "values", 0 ) +
      		" - $" + $( "#slider-price" ).slider( "values", 1 ) );
  			});

  			$(function() {
			    $( "#slider-weight" ).slider({
			      range: true,
			      min: 5,
			      max: 32,
			      values: [ <%= params[:min_denim_weight].present? ? params[:min_denim_weight] : 		   5 %>, 
			      			<%= params[:max_denim_weight].present? ? params[:max_denim_weight] : 32 %> ],
			      slide: function( event, ui ) {
			      	$( "#amount-weight" ).val(ui.values[ 0 ] + " oz - " + ui.values[ 1 ] + " oz" );
			        $( "#min_denim_weight" ).val(ui.values[0]);
			        $( "#max_denim_weight" ).val(ui.values[1]);
			      }
			    });
			    $( "#amount-weight" ).val($( "#slider-weight" ).slider( "values", 0 ) +
      		" oz - " + $( "#slider-weight" ).slider( "values", 1 ) + " oz" );
  			});
		})
	</script>
<% end %>

app/views/items/_single_slider.html.erb
<script>

$(function() {
    $( "#slider-name" ).slider({
      value: [ <%= params[name.to_sym].present? ? params[name.to_sym] : 32 %> ],
      min: min,
      max: max,
      step: step,
      slide: function( event, ui ) {
      	$( "#amount-name" ).val( ui.value + " inches" );
        $( "#name" ).val(ui.value);
      }
    });
    $( "#amount-name" ).val( $( "#slider-name" ).slider( "value" ) + " inches" );
});

</script>

app/views/items/_sizer_form.html.erb
<%= form_tag items_path, :method => 'get', :id => "test" do %>
    <div class"row">
        <div class="col-md-2">
            <%= select_tag :made_in, options_from_collection_for_select(Item.select(:made_in).uniq, :made_in, :made_in, :selected => params[:made_in]), :prompt => 'All Countries' %>
            <br>
            <%= select_tag :fabric_origin, options_from_collection_for_select(Item.select(:fabric_origin).uniq, :fabric_origin, :fabric_origin, :selected => params[:fabric_origin]), :prompt => 'All Mills' %>
            <br>
            <%= select_tag :color, options_from_collection_for_select(Item.select(:color).uniq, :color, :color, :selected => params[:color]), :prompt => 'All Colors' %>
            <br>
            <%= select_tag :brand, options_from_collection_for_select(Item.select(:brand).uniq, :brand, :brand, :selected => params[:brand]), :prompt => 'All Brands' %>
            <br>
        </div>
        <div class="col-md-4">
            <p>
              <label for="amount-waist">Waist Size:</label>
              <input type="text" id="amount-waist" style="border: 0; color: #f6931f; font-weight: bold;" />
            </p>
            <div class="slider-single">
                <div id="slider-waist"></div>
            </div><br>
            <%= hidden_field_tag :waist, params[:waist], value: params[:waist] || 32 %>
            <br>
            
            <p>
              <label for="amount-front_rise">Front Rise Size:</label>
              <input type="text" id="amount-front_rise" style="border: 0; color: #f6931f; font-weight: bold;" />
            </p>
            <div class="slider-single">
                <div id="slider-front_rise"></div>
            </div><br>
            <%= hidden_field_tag :front_rise, params[:front_rise], value: params[:front_rise] || 10 %>
            <br>

            <p>
              <label for="amount-thigh">Thigh Size:</label>
              <input type="text" id="amount-thigh" style="border: 0; color: #f6931f; font-weight: bold;" />
            </p>
            <div class="slider-single">
                <div id="slider-thigh"></div>
            </div><br>
            <%= hidden_field_tag :thigh, params[:thigh], value: params[:thigh] || 11 %>
            <br>
            
            <p>
              <label for="amount-knee">Knee Size:</label>
              <input type="text" id="amount-knee" style="border: 0; color: #f6931f; font-weight: bold;" />
            </p>
            <div class="slider-single">
                <div id="slider-knee"></div>
            </div><br>
            <%= hidden_field_tag :knee, params[:knee], value: params[:knee] || 8 %>
            <br>
            
            <p>
              <label for="amount-leg_opening">Leg Opening Size:</label>
              <input type="text" id="amount-leg_opening" style="border: 0; color: #f6931f; font-weight: bold;" />
            </p>
            <div class="slider-single">
                <div id="slider-leg_opening"></div>
            </div><br>
            <%= hidden_field_tag :leg_opening, params[:leg_opening], value: params[:leg_opening] || 8.2 %>
            <br>
        </div>
        <div class-"col-md-4">
            <p>
              <label for="amount-price">Price range:</label>
              <input type="text" id="amount-price" style="border: 0; color: #f6931f; font-weight: bold;" />
            </p>
            <div id="slider-price"></div>
            <%= hidden_field_tag :min_price, params[:min_price], value: params[:min_price] || 0 %>
            <%= hidden_field_tag :max_price, params[:max_price], value: params[:max_price] || 500 %>
            <br>
            <p>
              <label for="amount-weight">Denim weight:</label>
              <input type="text" id="amount-weight" style="border: 0; color: #f6931f; font-weight: bold;" />
            </p>
            <div id="slider-weight"></div>
            <%= hidden_field_tag :min_denim_weight, params[:min_denim_weight], value: params[:min_denim_weight] || 5 %>
            <%= hidden_field_tag :max_denim_weight, params[:max_denim_weight], value: params[:max_denim_weight] || 32 %>
            <br>
            Sanforized<br>
            <%= radio_button_tag :sanforized, true, 
                        (params[:sanforized] == "true" ? true : false) %>
            <%= label_tag(:sanforized_true, "Yes") %>
            <%= radio_button_tag :sanforized, false, 
                        (params[:sanforized] == "false" ? true : false) %>
            <%= label_tag(:sanforized_false, "No") %>
            <%= radio_button_tag :sanforized, "none", 
                        (params[:sanforized] == nil || 
                         params[:sanforized] == "none" ? true : false) %>
            <%= label_tag(:sanforized_none, "No Preference") %>
            <br>
            Selvedge<br>
            <%= radio_button_tag :selvedge, true, 
                        (params[:selvedge] == "true" ? true : false) %>
            <%= label_tag(:selvedge_true, "Yes") %>
            <%= radio_button_tag :selvedge, false, 
                        (params[:selvedge] == "false" ? true : false) %>
            <%= label_tag(:selvedge_false, "No") %>
            <%= radio_button_tag :selvedge, "none", 
                        (params[:selvedge] == nil || 
                         params[:selvedge] == "none" ? true : false) %>
            <%= label_tag(:selvedge_none, "No Preference") %>
        <br><br><br><br><br><br><br>
        </div>
    </div>
    <%= submit_tag "Search", :name => nil, class: "btn, btn-primary" %>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/edit.html.erb
<%= render 'layouts/header' %>

<div class="col-md-6"
<h1>Edit an existing Item in the database</h1>

<%= form_for @item do |f| %>

	<%= f.text_field :name, placeholder: "Model" %>
	<br>
	<%= f.text_field :brand, placeholder: "Brand" %>
	<br>
	<%= f.text_field :tag_size, placeholder: "Tagged Size" %>
	<br>
	<%= f.text_field :waist, placeholder: "Waist" %>
	<br>
	<%= f.text_field :front_rise, placeholder: "Front Rise" %>
	<br>
	<%= f.text_field :thigh, placeholder: "Thigh" %>
	<br>
	<%= f.text_field :knee, placeholder: "Knee" %>
	<br>
	<%= f.text_field :leg_opening, placeholder: "Leg Opening" %>
	<br>
	<%= f.text_field :inseam, placeholder: "Inseam" %>
	<br>
	<%= f.text_field :denim_weight, placeholder: "Denim Weight" %>
	<br>
	<%= f.check_box :sanforized %> The Jean is Sanforized
	<br>
	<%= f.check_box :stretch %> The Jean is Stretchy
	<br>
	<%= f.check_box :selvedge %> The Jean is selvedge
	<br>
	<%= f.text_field :color, placeholder: "Color" %>
	<br>
	<%= f.text_field :fabric_origin, placeholder: "Fabric country" %>
	<br>
	<%= f.text_field :made_in, placeholder: "Manufacturing country" %>
	<br>
	<%= f.text_field :price, placeholder: "Price" %>
	<br>
	<%= f.text_field :link, placeholder: "Link" %>
	<br>
	<%= f.submit "Save Item", class: "btn btn-medium btn-primary" %>

<% end %>

</div>

app/views/items/index.html.erb
<%= render 'scripts' %>

<br>

<div class="col-md-12">

<br>

<%= render 'sizer_form' %>

<br>

<!-- <b>Waist:</b>			<%#= number_with_precision(@waist, :precision => 4) %><br>
<b>Front Rise:</b>    <%#= number_with_precision(@front_rise, :precision => 4) %><br>
<b>Thigh:</b> 		<%#= number_with_precision(@thigh, :precision => 4) %><br>
<b>Knee:</b>			<%#= number_with_precision(@knee, :precision => 4) %><br>
<b>Leg Opening:</b>   <%#= number_with_precision(@leg_opening, :precision => 4) %><br> -->

<h2>All the items</h2>

<%= render 'index_table' %>

<%= link_to "New", new_item_path %>

</div>

app/views/items/new.html.erb
<%= render 'layouts/header' %>

<div class="col-md-6">

<h1>Enter a new Item into the database</h1>

<%= form_for @item do |f| %>

	<%= f.text_field :name, placeholder: "Model" %>
	<br>
	<%= f.text_field :brand, placeholder: "Brand" %>
	<br>
	<%= f.text_field :tag_size, placeholder: "Tagged Size" %>
	<br>
	<%= f.text_field :waist, placeholder: "Waist" %>
	<br>
	<%= f.text_field :front_rise, placeholder: "Front Rise" %>
	<br>
	<%= f.text_field :thigh, placeholder: "Thigh" %>
	<br>
	<%= f.text_field :knee, placeholder: "Knee" %>
	<br>
	<%= f.text_field :leg_opening, placeholder: "Leg Opening" %>
	<br>
	<%= f.text_field :inseam, placeholder: "Inseam" %>
	<br>
	<%= f.text_field :denim_weight, placeholder: "Denim Weight" %>
	<br>
	<%= f.check_box :sanforized %> The Jean is Sanforized
	<br>
	<%= f.check_box :stretch %> The Jean is stretchy
	<br>
	<%= f.check_box :selvedge %> The Jean is selvedge
	<br>
	<%= f.text_field :color, placeholder: "Color" %>
	<br>
	<%= f.text_field :fabric_origin, placeholder: "Fabric country" %>
	<br>
	<%= f.text_field :made_in, placeholder: "Manufacturing country" %>
	<br>
	<%= f.text_field :price, placeholder: "Price" %>
	<br>
	<%= f.text_field :link, placeholder: "Link" %>
	<br>
	<%= f.submit "Save Item" %>

<% end %>

</div>

app/views/items/show.html.erb
<%= render 'layouts/header' %>


<div class="col-md-12">

		<%= form_tag item_path, :method => 'get', :id => "parse" do %>
      <p>
        <%= text_area_tag :parse, params[:parse], placeholder: "Put in formatted jeans to get parsed jeans" %>
        <%= submit_tag "Parse", :name => nil, class: "btn btn-medium btn-primary" %>
      </p>
    <% end %>
    tag_size: <%= @tag_size %>,<br>
    waist: <%= @waist %>,<br>
    front_rise: <%= @front_rise %>,<br>
    thigh: <%= @thigh %>,<br>
    knee: <%= @knee %>,<br>
    leg_opening: <%= @leg_opening %>,<br> 
    inseam: <%= @inseam %>,<br>

<h1><%= @item.name %></h1>

<b>Name:  </b>
	<%= @item.name %><br>
<b>Brand:  </b>
	<%= @item.brand %><br>
<b>Tag Size:  </b>
	<%= @item.tag_size %><br>
<b>Waist:  </b>
	<%= @item.waist %><br>
<b>Front Rise: </b> 
	<%= @item.front_rise %><br>
<b>Thigh:  </b>
	<%= @item.thigh %><br>
<b>Knee:  </b>
	<%= @item.knee %><br>
<b>Leg Opening: </b> 
	<%= @item.leg_opening %><br>
<b>Inseam:  </b>
	<%= @item.inseam %><br>
<b>Color:  </b>
	<%= @item.color %><br>
<b>Weight</b>
	<%= @item.denim_weight %><br>
<b>Sanforized:  </b>
	<%= @item.sanforized %><br>
<b>Stretch:  </b>
	<%= @item.stretch %><br>
<b>Selvedge:  </b>
	<%= @item.selvedge %><br>
<b>Price:  </b>
	<%= @item.price %><br>
<b>Fabric Origin:  </b>
	<%= @item.fabric_origin %><br>
<b>Manufacturing Country:  </b>
	<%= @item.made_in %><br>
<b>Color:  </b>
	<%= @item.color %><br>
<b>More Info:  </b>
	<%= @item.link %><br>

</div>

app/views/layouts/_header.html.erb
<div class="contain-to-grid">
  <nav class="top-bar">
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h1><%= link_to "Home", root_path %></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
  </nav>
</div>

app/views/static_pages/_jean.html.erb
<div class="row">
	<div class="large-12 columns">
		<b><%= jean.model.brand %></b>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<%= jean.model.name %> (true waist <%= jean.waist %>)
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		$<%= jean.model.price %>	
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<%= jean.model.fit %>	
	</div>
</div>